server:
  port: 7001

# Eureka配置
eureka:
  instance:
    hostname: www.eureka7001.com  #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向注册中心注册自己
    fetch-registry: false #如果是false,则表示自己为注册中心
    service-url:
      # 单机监控页面  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群  在7001里挂载7002和7003
      defaultZone: http://www.eureka7002.com:7002/eureka/,http://www.eureka7003.com:7003/eureka/


